model:
  name: tf
  args:
    scale_height: 96
    attn_size: 512
    nhead: 8
    dim_feedforward: 4096
    dropout: 0.1
    encoder_nlayers: 2
    decoder_nlayers: 2
    use_encoder: true
    use_pe_text: true
    use_pe_image: true
    use_stn: true
    use_aspp: false
