model:
  name: tf
  args:
    scale_height: 96
    max_length: 15
    attn_size: 512
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    encoder_nlayers: 1
    decoder_nlayers: 1
    use_encoder: false
    use_pe_text: false
    use_pe_image: false
