defaults:
    vocab: vnondb_vocab_flatten
    dataset: vnondb
    cnn: resnet
    model: tf
    optimizer: adam
    lr_scheduler: plateau
    save_by: CER # One of CER, WER, Loss
    batch_size: 16
    max_epochs: 50
