common:
    dataset: rimes
    cnn: custom
    optimizer: adam
    batch_size: 4
    scale_height: 32
    max_length: 50
    use_handcraft: False

    n_epochs_decrease_lr: 5
    start_learning_rate: 1.0e-3
    end_learning_rate: 1.0e-11
    max_epochs: 50
    weight_decay: 0
    momentum: 0.9

custom:

tf:
    attn_size: 512
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    encoder_nlayers: 1
    decoder_nlayers: 1

