common:
    dataset: rimes_line
    cnn: resnet
    optimizer: adam
    flatten_type:  # flattening_1, flattening_2, or leave blank
    batch_size: 16
    scale_height: 96
    use_handcraft: False

    n_epochs_decrease_lr: 5
    start_learning_rate: 1.0e-3
    end_learning_rate: 1.0e-11
    max_epochs: 50
    weight_decay: 0
    momentum: 0.9

densenet:
    version: densenet161
    memory_efficient: True

resnet:
    version: resnet50

efficientnet:
    pretrained_name: efficientnet-b0

resnext:
    version: resnext50

custom:

tf:
    max_length: 200
    attn_size: 512
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    encoder_nlayers: 1
    decoder_nlayers: 1
    use_encoder: false
    use_pe_text: false
    use_pe_image: false

