dataset: vnondb
cnn: densenet
optimizer: RMSprop
batch_size: 32
scale_height: 128
max_length: 10
use_handcraft: False

n_epochs_decrease_lr: 5
start_learning_rate: 1.0e-5
end_learning_rate: 1.0e-11
max_epochs: 50
weight_decay: 0

densenet:
    depth: 4
    n_blocks: 3
    growth_rate: 96

s2s:
    hidden_size: 256
    attn_size: 256
