common:
    dataset: vnondb
    cnn: densenet
    optimizer: adam
    batch_size: 16
    scale_height: 96 
    max_length: 10
    use_handcraft: False

    n_epochs_decrease_lr: 5
    start_learning_rate: 1.0e-4
    end_learning_rate: 1.0e-11
    max_epochs: 50
    weight_decay: 0
    momentum: 0.9

densenet:

tf:
    attn_size: 512
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    encoder_nlayers: 1
    decoder_nlayers: 1

