common:
    dataset: vnondb
    cnn: densenet
    optimizer: sgd
    batch_size: 32
    scale_height: 96 
    max_length: 10
    use_handcraft: False

    n_epochs_decrease_lr: 5
    start_learning_rate: 1.0e-2
    end_learning_rate: 1.0e-11
    max_epochs: 50
    weight_decay: 1.0e-4
    momentum: 0.9

densenet:
    depth: 4
    n_blocks: 3
    growth_rate: 96

tf:
    attn_size: 256
    use_encoder: False
    use_FFNN: True
    encoder_attn: scaledotproduct
    decoder_attn: additive
    encoder_decoder_attn: additive
    direct_additive: False
    encoder_nhead: 8
    decoder_nhead: 10
    encoder_decoder_nhead: 8
    encoder_nlayers: 1
    decoder_nlayers: 1

