common:
    model: tf_full
    dataset: vnondb
    cnn: resnet
    optimizer: adam
    flatten_type:  # flattening_1, flattening_2, or leave blank
    batch_size: 16
    scale_height: 96
    max_epochs: 50

adam:
    lr: 1.0e-5
    weight_decay: 0

resnet:
    version: resnet50

tf_full:
    scale_height: 96
    max_length: 15
    use_adaptive_pool_cnn: false
    attn_size: 512
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    encoder_nlayers: 6
    decoder_nlayers: 6
    use_encoder: false
    use_pe_text: false
    use_pe_image: false
