common:
    dataset: vnondb_line
    cnn: resnet
    optimizer: RMSprop
    batch_size: 8
    scale_height: 64
    max_length: 160

    n_epochs_decrease_lr: 5
    start_learning_rate: 1.0e-5
    end_learning_rate: 1.0e-11
    max_epochs: 50
    weight_decay: 0

resnet:

s2s:
    hidden_size: 256
    attn_size: 256
    attention: additive
    teacher_forcing_ratio: 0.5
