common:
    dataset: vnondb
    cnn: efficientnet
    optimizer: adam
    batch_size: 16
    scale_height: 96 
    max_length: 10
    use_handcraft: False

    n_epochs_decrease_lr: 5
    start_learning_rate: 1.0e-4
    end_learning_rate: 1.0e-11
    max_epochs: 50
    weight_decay: 0
    momentum: 0.9

tf:
    attn_size: 512
    use_encoder: False
    use_FFNN: True
    encoder_attn: scaledotproduct
    decoder_attn: scaledotproduct
    encoder_decoder_attn: scaledotproduct
    direct_additive: False
    encoder_nhead: 8
    decoder_nhead: 1
    encoder_decoder_nhead: 8
    encoder_nlayers: 1
    decoder_nlayers: 1

