dataset:
  name: vnondb_line
  args:

  train:
    csv: data/VNOnDB/line/train_line_new.csv
    image_folder: data/VNOnDB/line/train_line

  validation:
    csv: data/VNOnDB/line/validation_line_new.csv
    image_folder: data/VNOnDB/line/validation_line

  test:
    csv: data/VNOnDB/line/test_line_new.csv
    image_folder: data/VNOnDB/line/test_line