dataset:
  name: vnondb_line
  args:
    flatten_type:  # flattening_1, flattening_2, or leave blank
    train_csv: data/VNOnDB/line/train_line.csv

  train:
    csv: data/VNOnDB/line/train_line.csv
    image_folder: data/VNOnDB/line/train_line

  validation:
    csv: data/VNOnDB/line/validation_line.csv
    image_folder: data/VNOnDB/line/validation_line

  test:
    csv: data/VNOnDB/line/test_line.csv
    image_folder: data/VNOnDB/line/test_line