dataset:
  name: vnondb
  args:

  train:
    csv: data/VNOnDB/word/train_word_new.csv
    image_folder: data/VNOnDB/word/train_word

  validation:
    csv: data/VNOnDB/word/validation_word_new.csv
    image_folder: data/VNOnDB/word/validation_word

  test:
    csv: data/VNOnDB/word/test_word_new.csv
    image_folder: data/VNOnDB/word/test_word